services:
  fr_api:
    container_name: fr_api
    build:
      context: .
    image: fr_api
    networks:
      - app_net
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=admin
      - MONGODB_INITDB_ROOT_PASSWORD=admin
    networks:
      - app_net
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })" ]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  mongoexpress:
    container_name: mongoexpress
    image: mongo-express
    networks:
      - app_net
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin@mongodb/
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    depends_on:
      mongodb:
        condition: service_healthy

networks:
  app_net:
    name: app_net
    driver: bridge

volumes:
  mongodb_data:
    name: mongodb_data
    driver: local
